name: Build Android App (Debug APK)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Limpar Espaço e Instalar Dependências
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 python3-dev \
          ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
          libgstreamer1.0-dev openjdk-17-jdk ant autoconf automake libtool pkg-config \
          libunwind-dev libcrypt1 expect unzip wget

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Buildozer e Dependências Python
        run: |
          pip install --upgrade pip
          pip install cython==0.29.33 buildozer==1.5.0

      - name: Configurar Android SDK e NDK 25b
        run: |
          ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          mkdir -p $ANDROID_SDK_ROOT
          
          # Baixa e instala o NDK 25b
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk25b.zip
          unzip -q ndk25b.zip -d $ANDROID_SDK_ROOT/ndk
          
          export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/android-ndk-r25b
          export ANDROIDNDK=$ANDROID_NDK_HOME
          export PATH=$ANDROID_NDK_HOME:$PATH
          
          # Prepara configurações do Android
          mkdir -p ~/.android && touch ~/.android/repositories.cfg

      - name: Gerar APK Debug
        run: |
          export ACLOCAL_PATH=/usr/share/aclocal
          export ANDROIDNDK=$ANDROID_NDK_HOME
          
          # Build do APK debug
          buildozer android debug
        env:
          ANDROIDNDK: ${{ env.ANDROID_NDK_HOME }}

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: NeuralFaceHD_Debug_APK
          path: bin/*.apk
