name: Build APK Oficial

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.json'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          sudo apt-get install -y libgstreamer1.0-gstreamer-lite1.0-dev libgstreamer-plugins-base1.0-dev autoconf automake libtool pkg-config cmake
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 setuptools

      - name: Build with Buildozer
        run: |
          yes | buildozer -v android release
        env:
          # Isso garante que ele use as senhas e a chave que estão no seu buildozer.spec
          APP_ANDROID_KEYSTORE: neuralface.keystore
          APP_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          APP_ANDROID_KEYALIAS_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NeuralFaceHD-Oficial
          path: bin/*.apk
